server:
  port: ${SERVER_PORT}

spring:
  application:
    name: ${SERVICE_NAME}
  webflux:
    base-path: ${URL_PREFIX}

springdoc:
  api-docs:
    path: ${API_PATH}
  swagger-ui:
    path: ${SWAGGER_PATH}
